name: unit-test

on:
  push:
    branch: unit-testing
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  gcc:
    runs-on: ubuntu-latest
    steps:
      - name: Build pFUnit
        run: |
          git clone --depth 1 --branch v4.10.0 https://github.com/Goddard-Fortran-Ecosystem/pFUnit.git
          cd pFUnit
          cmake -B./build -S.
          cd build
          make install

      - name: Checkout history
        uses: actions/checkout@v4

      - name: Build
        run: |
          cmake -DCMAKE_PREFIX_PATH=/pFUnit/build/installed -B./build -S.
          cd build
          make
          ctest -V --output-junit res.xml
